apiVersion: apps/v1
kind: Deployment
metadata:
  name: py
  labels:
    app: py
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py
  template:
    metadata:
      labels:
        app: py
    spec:
      containers:
      - name: echo
        image: artifactory.shapingdixonsretail.com/oborim01/non_kokurice@sha256:ad8d3b7b0b0aaaa49e8fa7cc49ec9b5a212fdf871918bb8406eacbafe659afed
        imagePullPolicy: Always
        env:
          - name: DOWNSTREAM_URL
            value: "http://downstream:3333"
        ports:
        - containerPort: 9002
---
kind: Service
apiVersion: v1
metadata:
  name: py
spec:
  selector:
    app: py
  ports:
  # Default port used by the image
  - port: 9002
    name: http

# Istio 
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: py-gateway
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - port:
      number: 9002
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: py-service-ingress
spec:
  hosts: 
  - '*'
  gateways:
  - py-gateway
  http:
  - match:
    - uri:
        prefix: "/py"
    route:
    - destination:
        host: py
